# Generated by Django 5.2.4 on 2026-04-28 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('fy', 'FY'), ('sy', 'SY'), ('ty', 'TY')], max_length=10)),
                ('year', models.CharField(choices=[('2022', '2022-23'), ('2023', '2023-24'), ('2024', '2024-25'), ('2025', '2025-26')], max_length=10)),
                ('semester', models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('sem3', 'Semester 3'), ('sem4', 'Semester 4'), ('sem5', 'Semester 5'), ('sem6', 'Semester 6')], default='sem1', max_length=10)),
                ('subject', models.CharField(default='Unknown', max_length=100)),
                ('theory_pdf', models.FileField(blank=True, upload_to='assignments/theory/')),
                ('practical_pdf', models.FileField(blank=True, upload_to='assignments/practical/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
                ('link_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news_files/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year')], max_length=2)),
                ('exam', models.CharField(default='Midterm', max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('upload_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_name', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=2)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('2022', '2022-23'), ('2023', '2023-24'), ('2024', '2024-25'), ('2025', '2025-26')], max_length=4)),
                ('file', models.FileField(upload_to='syllabus_files/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UnitTestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('fy', 'FY'), ('sy', 'SY'), ('ty', 'TY')], max_length=10)),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('semester', models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('sem3', 'Semester 3'), ('sem4', 'Semester 4'), ('sem5', 'Semester 5'), ('sem6', 'Semester 6')], default='sem1', max_length=10)),
                ('subject', models.CharField(default='Maths', max_length=100)),
                ('theory_pdf', models.FileField(blank=True, upload_to='unit_tests/theory/')),
                ('practical_pdf', models.FileField(blank=True, upload_to='unit_tests/practical/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
