# Generated by Django 5.2.4 on 2026-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0013_reconcile_legacy_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='practical_pdf',
            field=models.FileField(blank=True, max_length=2048, upload_to='assignments/practical/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='theory_pdf',
            field=models.FileField(blank=True, max_length=2048, upload_to='assignments/theory/'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='attachment',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to='news_files/'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='pdf_file',
            field=models.FileField(max_length=2048, upload_to='question_papers/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(max_length=2048, upload_to='syllabus_files/'),
        ),
        migrations.AlterField(
            model_name='unittestupload',
            name='practical_pdf',
            field=models.FileField(blank=True, max_length=2048, upload_to='unit_tests/practical/'),
        ),
        migrations.AlterField(
            model_name='unittestupload',
            name='theory_pdf',
            field=models.FileField(blank=True, max_length=2048, upload_to='unit_tests/theory/'),
        ),
    ]
