# Generated by Django 5.2.4 on 2026-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0014_alter_assignment_practical_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='semester',
            field=models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('sem3', 'Semester 3'), ('sem4', 'Semester 4'), ('sem5', 'Semester 5'), ('sem6', 'Semester 6')], default='sem1', max_length=10),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='semester',
            field=models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('sem3', 'Semester 3'), ('sem4', 'Semester 4'), ('sem5', 'Semester 5'), ('sem6', 'Semester 6')], default='sem1', max_length=10),
        ),
    ]
