"""
Django settings for vp project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue

        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("'").strip('"'))


load_env_file(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def origin_to_host(origin):
    candidate = origin.strip()
    if not candidate:
        return ""

    if "://" not in candidate:
        return candidate.split(":", 1)[0]

    return urlparse(candidate).hostname or ""


def host_to_origin(host):
    candidate = host.strip()
    if not candidate:
        return ""

    if "://" in candidate:
        return candidate.rstrip("/")

    return f"https://{candidate}"


def unique(values):
    return list(dict.fromkeys(value for value in values if value))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-7fv0y=$x6e5b&bhg3r(0f9y=633v#otltjgkbuw@6)jmx2(d4c",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

VERCEL_DEPLOYMENT_HOSTS = unique(
    [
        os.getenv("VERCEL_URL", "").strip(),
        os.getenv("VERCEL_BRANCH_URL", "").strip(),
        os.getenv("VERCEL_PROJECT_PRODUCTION_URL", "").strip(),
    ]
)
VERCEL_DEPLOYMENT_ORIGINS = unique(host_to_origin(host) for host in VERCEL_DEPLOYMENT_HOSTS)
DEFAULT_VERCEL_PUBLIC_URL = next(iter(VERCEL_DEPLOYMENT_ORIGINS), "")

BACKEND_PUBLIC_URL = os.getenv(
    "BACKEND_PUBLIC_URL",
    DEFAULT_VERCEL_PUBLIC_URL,
).rstrip("/")
FRONTEND_PUBLIC_URL = os.getenv(
    "FRONTEND_PUBLIC_URL",
    BACKEND_PUBLIC_URL or DEFAULT_VERCEL_PUBLIC_URL,
).rstrip("/")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

ALLOWED_HOSTS = unique(
    [
        "localhost",
        "127.0.0.1",
        "[::1]",

        # Allow all Vercel deployments
        ".vercel.app",

        # Your production domain
        "vidyarthi-portal-complete.vercel.app",

        # Public URLs
        origin_to_host(BACKEND_PUBLIC_URL),
        origin_to_host(FRONTEND_PUBLIC_URL),

        # Deployment hosts from environment
        *VERCEL_DEPLOYMENT_HOSTS,

        # Render fallback
        os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip(),

        # Additional hosts from env
        *env_list("DJANGO_ALLOWED_HOSTS"),
    ]
)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'vp',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vp.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = "vp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}",
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=bool(DATABASE_URL) and not DATABASE_URL.startswith("sqlite") and not DEBUG,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
FRONTEND_DIST_DIR = BASE_DIR / "frontend" / "dist"
FRONTEND_STATIC_INDEX = FRONTEND_DIST_DIR / "index.html"
COLLECTED_STATIC_INDEX = Path(STATIC_ROOT) / "index.html"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [path for path in [FRONTEND_DIST_DIR] if path.exists()]
STORAGES = {
    "default": {
        "BACKEND": "vp.storage.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Keep admin/static templates working even if a deployment is missing a fresh
# manifest, while still using hashed assets whenever collectstatic has run.
WHITENOISE_MANIFEST_STRICT = env_bool("WHITENOISE_MANIFEST_STRICT", False)


LOGIN_REDIRECT_URL = "/dashboard"
LOGIN_URL = "/login"
LOGOUT_REDIRECT_URL = "/login"

default_frontend_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://vidyarthi-portal-complete.vercel.app",
    *VERCEL_DEPLOYMENT_ORIGINS,
]
if FRONTEND_PUBLIC_URL:
    default_frontend_origins.append(FRONTEND_PUBLIC_URL)

CORS_ALLOWED_ORIGINS = unique(
    default_frontend_origins + env_list("CORS_ALLOWED_ORIGINS")
)
CORS_ALLOWED_ORIGIN_REGEXES = env_list("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = unique(
    [
        *default_frontend_origins,
        BACKEND_PUBLIC_URL,
        FRONTEND_PUBLIC_URL,
        *env_list("CSRF_TRUSTED_ORIGINS"),
    ]
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
USE_CROSS_SITE_COOKIES = env_bool("DJANGO_CROSS_SITE_COOKIES", False)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "None" if USE_CROSS_SITE_COOKIES and not DEBUG else "Lax"
CSRF_COOKIE_SAMESITE = "None" if USE_CROSS_SITE_COOKIES and not DEBUG else "Lax"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
